export enum Anemities {
    FREE_WIFI = 'Free WiFi',
    FREE_BREAKFAST = 'Free breakfast',
    RESTAURANT = 'Restaurant',
    BAR = 'Bar',
    KID_FRIENDLY ='Kid-friendly',
    PET_FRIENDLY = 'Pet-friendly',
    FREE_PARKING = 'Free parking',
    PARKING = 'Parking',
    EV_CHARGER = 'EV charger',
    ROOM_SERVICE = 'Room service',
    FITNESS_CENTER = 'Fitness center',
    SPA = 'Spa',
    POOL = 'Pool',
    INDOOR_POOL = 'Indoor pool',
    OUTDOOR_POOL = 'Outdoor pool',
    AIR_CONDITIONED = 'Air-conditioned',
    WHEELCHAIR_ACCESSIBLE = 'Wheelchair accessible',
    BEACH_ACCESS = 'Beach access',
    ALL_INCLUSIVE_AVAILABLE = 'All-inclusive available',
}